spring:
  application:
    name: nebula-core

  datasource:
    # Forçando a conexão no banco que SABEMOS que existe
    url: jdbc:mysql://localhost:3306/nebula?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # Mostra o SQL no console pra gente ter certeza
    show-sql: true
    # Força o Hibernate a criar as tabelas se não existirem
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect